Build against 23-ea
Oracle broke the url to the Apidocs for 22-ea (https://jdk.java.net/22/
-> https://download.java.net/java/early_access/jdk22/docs/api/) and
this breaks the builds
https://github.com/apache/wicket/actions/runs/8127287410/job/22211950370?pr=800:

```
Error:  Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.6.3:jar (attach-javadocs) on project wicket-util: MavenReportException: Error while generating Javadoc:
Error:  Exit code: 1
Error: [ERROR] error: Error fetching URL: https://download.java.net/java/early_access/jdk22/docs/api/ (java.io.FileNotFoundException: https://download.java.net/java/early_access/jdk22/docs/api/package-list)
Error: [ERROR] 1 error
Error:  Command line was: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/22.0.0-ea.36.0.ea/x64/bin/javadoc -J-Xmx256m -J-Xms128m @options @packages
Error:
Error:  Refer to the generated Javadoc files in '/home/runner/work/wicket/wicket/wicket-util/target/apidocs' dir.
Error:
```

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>