Do not run JS tests on Github Actions
The tests hang since a while ...

https://github.com/apache/wicket/actions/runs/3892116129/jobs/6652898002

INFO]
[INFO] Running "jshint:gymTestsJs" (jshint) task
[INFO] >> 12 files lint free.
[INFO]
[INFO] Running "jshint:grunt" (jshint) task
[INFO] >> 1 file lint free.
[INFO]
[INFO] Running "connect:server" (connect) task
[INFO] Started connect web server on http://localhost:38887
[INFO]
[INFO] Running "qunit:all" (qunit) task
Error: The operation was canceled.

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>