Bump Mockito to 5.11.0
Trying to get over this error:
```
Error:    RedirectRequestHandlerTest.<init>:39 Mockito
Mockito cannot mock this class: class org.apache.wicket.request.http.WebResponse.
If you're not sure why you're getting this error, please open an issue on GitHub.
Java               : 23
JVM vendor name    : Eclipse Adoptium
JVM vendor version : 23-beta+12-ea
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 23-beta+12-ea
JVM info           : mixed mode, sharing
OS name            : Linux
OS version         : 6.5.0-1015-azure
You are seeing this disclaimer because Mockito is configured to create inlined mocks.
You can learn about inline mocks and their limitations under item #39 of the Mockito class javadoc.
Underlying exception : org.mockito.exceptions.base.MockitoException: Could not modify all classes [class org.apache.wicket.request.Response, class org.apache.wicket.request.http.WebResponse, class java.lang.Object]
```

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>